workflows:
  kivy-build:
    name: Build Kivy APK
    max_build_duration: 30
    environment:
      vars:
        BUILDOZER_SPEC: buildozer.spec
    dependencies:
      packages:
        - zip
        - unzip
        - openjdk-11-jdk
        - python3-pip
        - build-essential
      pip_packages:
        - --upgrade pip
        - buildozer
        - cython
    scripts:
      - buildozer android debug
    artifacts:
      - bin/*.apk
