name: dz_shopping
description: A Flutter ecommerce app connected to Firebase.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase packages
  firebase_core: ^2.31.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  firebase_storage: ^11.6.0

  # UI and UX
  cupertino_icons: ^1.0.2

  # Image picker (for admin to upload product images)
  image_picker: ^1.1.1

  # State management (optional, if needed)
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
